env:
  grid_dims: 32x32
  n_starts: 5
  n_goals: 5
  n_bridges: 40
  n_episode_steps: 75
  configs_to_consider: 25
  action_success_rate: 0.50

agent:
  n_episodes: 200
  n_training_steps: 10000
  n_episodes_testing: 25

  dqn:
    alpha: 0.0002
    dropout: 0.2
    gamma: 0.99
    epsilon: 0.325
    batch_size: 4
    hidden_dims: 128
    n_hidden_layers: 1
    buffer_size: 5000
    target_update_freq: 10
