env:
  n_steps: 10
  granularity: 0.25
  action_cost: 0.01
  configs_to_consider: 1
  failed_path_cost: 0
  util_multiplier: 1

dqn:
  alpha: 0.0003
  gamma: 0.99
  epsilon: 0.325
  batch_size: 128
  buffer_size: 1000
  target_update_freq: 2000

  sma_window: 50
  num_episodes: 500
  n_timesteps: 10000
  num_episodes_testing: 100
