env:
  map_name: 8x8
  n_bridges: 16
  n_steps: 12

  action_cost: 0.05
  configs_to_consider: 1
  action_success_rate: 0.75

q_table:
  alpha: 0.025
  gamma: 0.99
  epsilon: 0.25

  num_episodes: 500
  n_timesteps: 5000
  num_episodes_testing: 100
