env:
  granularity: 0.25
  failed_path_cost: 0
  safe_area_multiplier: 2
  n_episode_steps: 10
  configs_to_consider: 50

agent:
  n_episodes: 200
  n_training_steps: 10000
  n_episodes_testing: 3

  dqn:
    alpha: 0.0005
    dropout: 0.2
    gamma: 0.99
    epsilon: 0.25
    batch_size: 4
    hidden_dims: 128
    n_hidden_layers: 1
    buffer_size: 5000
    target_update_freq: 10
