env:
  map_name: 8x8
  n_bridges: 16
  n_steps: 12

  action_cost: 0.05
  configs_to_consider: 1
  action_success_rate: 0.75

dqn:
  gamma: 0.99
  alpha: 0.0001
  epsilon: 0.25
  batch_size: 128
  buffer_size: 15000
  target_update_freq: 2000

  sma_window: 50
  num_episodes: 500
  n_timesteps: 10000
  num_episodes_testing: 100
