env:
  step_value: 1
  over_penalty: 2
  max_noise: 10
  n_episode_steps: 300

agent:
  n_episodes: 1000
  n_training_steps: 10000
  n_episodes_testing: 20

  alpha: 0.2
  gamma: 0.99
  epsilon: 0.25
