env:
  n_steps: 100
  step_scale: 0.01
  over_penalty: 10
  under_penalty: 0.1
  complete_reward: 100

agent:
  alpha: 0.1
  gamma: 0.99
  epsilon: 0.25
  num_episodes: 500
  n_timesteps: 10000
  num_episodes_testing: 100
